### ISSUE TITLE
RestSharp 105.2 bug

### ISSUE THREAD

**Issue by ErriBrr** [reverentgeek/leankit-dotnet-client#1]
Hi,

With RestSharp in version 105.2 we have this exception : *'System.TypeLoadException'* because it's unable to load *'RestSharp.IAuthenticator'*

Thanks,

**Comment by reverentgeek** [comment]
Hi,

This repository is a work-in-progress for a new version of the LeanKit API Client that does not use RestSharp. You are probably referring to the [official LeanKit API Client](https://github.com/LeanKit/LeanKit.API.Client). If you are using the version of RestSharp that is referenced in by the project, you should not have any issues.

However, if you must use the latest version of RestSharp with your project, I believe `IAuthenticator` is still a part of RestSharp, just under a different namespace. You may need to update the reference in the [LeanKit API Client](https://github.com/LeanKit/LeanKit.API.Client) source code and recompile.

Best regards,
David
